question_data = [
    {"question":"Linus Torvalds created Linux and Git.","correct_answer":"True","incorrect_answers":"False"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.","correct_answer":"False","incorrect_answers":"True"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Pointers were not used in the original C programming language; they were added later on in C++.","correct_answer":"False","incorrect_answers":"True"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"RAM stands for Random Access Memory.","correct_answer":"True","incorrect_answers":"False"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Ada Lovelace is often considered the first computer programmer.","correct_answer":"True","incorrect_answers":"False"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Windows 7 operating system has six main editions.","correct_answer":"True","incorrect_answers":"False"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Windows ME operating system was released in the year 2000.","correct_answer":"True","incorrect_answers":"False"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.","correct_answer":"False","incorrect_answers":["True"]},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"Linux was first created as an alternative to Windows XP.","correct_answer":"False","incorrect_answers":"True"},
                 {"category":"Science: Computers","type":"boolean","difficulty":"easy","question":"The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;","correct_answer":"True","incorrect_answers":"False"},
    {"category":"Entertainment: Music","type":"boolean","difficulty":"easy","question":"The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.","correct_answer":"True","incorrect_answers":["False"]},{"category":"History","type":"boolean","difficulty":"medium","question":"In World War II, Hawker Typhoons served in the Pacific theater.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Geography","type":"boolean","difficulty":"medium","question":"The Southeast Asian island of Borneo is politically divided among 3 countries.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Film","type":"boolean","difficulty":"easy","question":"In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Film","type":"boolean","difficulty":"medium","question":"Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.","correct_answer":"False","incorrect_answers":["True"]},{"category":"Animals","type":"boolean","difficulty":"easy","question":"Cats have whiskers under their legs.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Politics","type":"boolean","difficulty":"hard","question":"Nazi Germany surrendered on Harry Truman&#039;s birthday while he was president.","correct_answer":"True","incorrect_answers":["False"]},{"category":"Entertainment: Video Games","type":"boolean","difficulty":"medium","question":"In &quot;League of Legends&quot;, there exists four different types of Dragon.","correct_answer":"False","incorrect_answers":["True"]},{"category":"General Knowledge","type":"boolean","difficulty":"medium","question":"&quot;Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.&quot; is a grammatically correct sentence.","correct_answer":"True","incorrect_answers":["False"]}
]